### ISSUE TITLE
geomap tiles not aligning properly in download

### ISSUE THREAD

**Issue by ranucame** [d3plus/d3plus-export#4]
Hello,

I've created a Geomap and I activated the option to download it (http://jsfiddle.net/ranucame/wtquj2yk/2/), the problem is when you download it, the background map doesn't fit with the geomap, how could fix it?

Thanks

**Comment by davelandry** [comment]
I believe this has been fixed. @ranucame please reopen this issue if it still persists for you in the latest version of d3plus-export.
